modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/Deftu/${mod_name}/issues"
license="LGPL-3.0-or-later"

[[mixins]]
    config = "mixins.${mod_id}.json"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    authors="Deftu"
    description="${mod_description}"

[[dependencies.${mod_id}]]
    modId="neoforge"
    mandatory=true
    versionRange="[1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${minor_mc_version}]"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="textile"
    mandatory=true
    versionRange="*"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="omnicore"
    mandatory=true
    versionRange="*"
    ordering="NONE"
    side="BOTH"
