name: Build and Comment on PR

on:
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches:
      - '**'
    paths-ignore:
      - 'README'
      - 'README.md'
      - 'LICENSE'
      - 'LICENSE-TEMPLATE'
      - 'LICENSE.md'
      - 'LICENSE-TEMPLATE.md'

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref }}'
  cancel-in-progress: false

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  build-and-comment:
    runs-on: ubuntu-latest
    outputs:
      comment_id: ${{ steps.comment-init.outputs.comment-id }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/merge

      - name: Find existing workflow comment
        uses: peter-evans/find-comment@v4
        id: find-comment
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: '<!-- workflow comment -->'

      - name: Render initial comment body
        id: render-initial
        uses: chuhlomin/render-template@v1.10
        with:
          template: './.github/assets/pull-request-responses/initial.md'
          vars: |
            build_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Post or update initial comment
        uses: peter-evans/create-or-update-comment@v5
        id: comment-init
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          edit-mode: replace
          body: ${{ steps.render-initial.outputs.result }}

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle

      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        id: upload-artifact
        with:
          name: Artifacts
          path: |
            build/libs/*.jar
            versions/*/build/libs/*.jar
          if-no-files-found: error

      - name: Render success comment body
        id: render-success
        uses: chuhlomin/render-template@v1.10
        with:
          template: './.github/assets/pull-request-responses/success.md'
          vars: |
            commit: ${{ github.event.pull_request.head.sha }}
            logs: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            download: ${{ steps.upload-artifact.outputs.artifact-url }}

      - name: Update comment with build results
        uses: peter-evans/create-or-update-comment@v5
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: ${{ steps.comment-init.outputs.comment-id }}
          edit-mode: replace
          body: ${{ steps.render-success.outputs.result }}

  comment-if-failed:
    needs: [ build-and-comment ]
    if: ${{ failure() }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: refs/pull/${{ github.event.pull_request.number }}/merge

      - name: Render failure comment body
        id: render-failure
        uses: chuhlomin/render-template@v1.10
        with:
          template: './.github/assets/pull-request-responses/failure.md'
          vars: |
            commit: ${{ github.event.pull_request.head.sha }}
            logs: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Update comment with failure results
        uses: peter-evans/create-or-update-comment@v5
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: ${{ needs.build-and-comment.outputs.comment_id }}
          edit-mode: replace
          body: ${{ steps.render-failure.outputs.result }}